server:
  port: 9091
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Param2050/test/tree/master/primary-config
          search-paths:
            - '*service'
