server:
  port: 9091
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Param2050/config.git
          search-paths:
            - '*nickfury-service'
            - '*zola-service'